### ISSUE TITLE
CleanupApplicationErrorsJobTest failing (presumably due to time zone differences)

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/dropwizard-application-errors#109]
It is 11/14/2021 at 6:51pm EST and both tests in `CleanupApplicationErrorsJobTest` are failing with errors like:

```
Argument(s) are different! Wanted:
applicationErrorDao.deleteResolvedErrorsBefore(
    <custom argument matcher>
);
-> at org.kiwiproject.dropwizard.error.job.CleanupApplicationErrorsJobTest.shouldDeleteResolvedExpiredErrors_WhenStrategyIsResolvedErrors(CleanupApplicationErrorsJobTest.java:45)
Actual invocations have different arguments:
applicationErrorDao.deleteResolvedErrorsBefore(
    2021-10-31T19:48:36.318091-04:00[America/New_York]
);
-> at org.kiwiproject.dropwizard.error.job.CleanupApplicationErrorsJob.runSafely(CleanupApplicationErrorsJob.java:29)
```

I am pretty sure this has to do with the fact that we just switched from EDT to EST last weekend, and 14 days ago was in EDT while we are - as I type this - now in EST. As a result, the date/time comparison is not working properly.

Regardless, we should figure out a way to make this pass consistently. This might require some design changes, e.g. maybe tp specify the time zone. Or, we could add "slack" into the test as a quick fix.

**Comment by sleberknight** [comment]
Added some logging to the class and the test:

```
19:48:16.554 [main] DEBUG o.k.d.e.j.CleanupApplicationErrorsJob - Deleted 0 expired resolved application errors before 2021-10-31T20:48:16.539144-04:00[America/New_York]
19:48:16.558 [main] INFO  o.k.d.e.j.CleanupApplicationErrorsJobTest - 14 days ago: 2021-10-31T19:48:16.558712-04:00[America/New_York]
```

From the logs above, the time difference is 1 hour, which seems to confirm my hypothesis about EDT versus EST. We are currently calling `ZonedDateTime.now().minusMinutes(expiration)` in the cleanup job class, while in the test we are simply saying `ZonedDateTime.now().minusDays(14)` (and the expiration is the default 14 days).

And, if I change the tests to calculate the past date/time using `minusMinutes` then the tests pass. So, maybe we should just calculate them in the same way in order to avoid the time zone issues.
